# Generated by Django 4.1.3 on 2022-11-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackUsername', models.CharField(max_length=200)),
                ('operation_type', models.CharField(choices=[('add', 'addition'), ('sub', 'subtraction'), ('div', 'division'), ('mul', 'multiplication')], max_length=200)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
