# Generated by Django 4.1.3 on 2022-11-04 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='operation_type',
        ),
        migrations.AddField(
            model_name='main',
            name='operationtype',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
