# Generated by Django 4.1.3 on 2022-11-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_main_operationtype_alter_main_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='operationtype',
            field=models.CharField(choices=[('addition', 'addition'), ('subtraction', 'subtraction'), ('division', 'division'), ('multiplication', 'multiplication')], max_length=200),
        ),
    ]
