# Generated by Django 4.1.3 on 2022-11-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_main_operationtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='operationtype',
            new_name='operation_type',
        ),
    ]
