# Generated by Django 4.1.3 on 2022-11-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_operationtype_main_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='main',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
